# baseURL = 'https://slush.systems/'
baseURL = 'https://slushsystems.fly.dev/'
languageCode = 'en-us'
title = 'slush.systems'
theme = 'terminal'
paginate = 20
enableGitInfo = true

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  #contentTypeName = "content/posts"

  # aqua blue cyan green lilac orange pink purple red yellow
  themeColor = "yellow"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = false

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # (default: true)
  oneHeadingSize = false

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents (default: false)
  # can be overridden in a page's front-matter
  Toc = false

  # set title for the table of contents (default: Table of Contents)
  # can be overridden in a page's front-matter
  TocTitle = "table of contents"

  # The GitInfo.Hash is appended to create a link to the commit on github
  githubCommitUrlPrefix = "https://github.com/jetpks/slush.systems/commit/"

[languages]
  [languages.en]
    languageName = "English"
    title = "slush.systems"
    subtitle = "Misadventures in technology"
    owner = "Eric Jacobs"
    keywords = ""
    copyright = "2023"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "slush.systems"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    noHl = false
    # style = 'dracula'
    tabWidth = 4

[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^nvim$']

